# TensorFlow Playground
## January 2023
### by Michelle (Chelle) Davies
This notebook is my environment to practive using TensorFlow's features. Eventually, I will build more specific projects. For now, there's no (intentional) cohesive narrative with these datasets.

In [1]:
# imports
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.9.1


## Starting with a tutorial on the basics
Source: https://www.tensorflow.org/tutorials/quickstart/beginner

In [2]:
# load the preloaded dataset
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
mnist

<module 'keras.api._v2.keras.datasets.mnist' from '/Users/michelledavies/opt/anaconda3/lib/python3.9/site-packages/keras/api/_v2/keras/datasets/mnist/__init__.py'>

Next, I'm going to build a model. These are the options:
1. Keras Sequential Model
2. Keras Functional API

I'm building a `tf.keras.Sequential` model.

In [4]:
# Build a tf.keras.Sequential model:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

2023-01-26 22:15:26.089551: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
# get predictions
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.36543489, -0.21234655,  0.4437616 , -0.1045904 ,  0.21694954,
         0.29611188, -0.3716327 , -0.2206865 , -0.3774851 , -0.08088484]],
      dtype=float32)

In [6]:
# The tf.nn.softmax function converts these logits to probabilities for each class:
probabilities = tf.nn.softmax(predictions).numpy()
probabilities

array([[0.13863203, 0.07779224, 0.1499272 , 0.08664314, 0.11950256,
        0.12934718, 0.06633751, 0.07714615, 0.06595041, 0.0887216 ]],
      dtype=float32)

In [7]:
# Define a loss function for training using losses.SparseCategoricalCrossentropy:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.0452552

Before training, configure and compile the model using Keras `Model.compile`. Set the optimizer class to adam, set the loss to the `loss_fn` function defined earlier, and specify a metric to be evaluated for the model by setting the metrics parameter to accuracy.

In [9]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

### Train and evaluate the model
Use the Model.fit method to adjust the model parameters and minimize the loss:

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3012 - accuracy: 0.9127
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1439 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1059 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0879 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0738 - accuracy: 0.9775


The `Model.evaluate` method checks the model's performance, usually on a validation set or test set.

In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0738 - accuracy: 0.9778 - 434ms/epoch - 1ms/step


[0.07378516346216202, 0.9778000116348267]

The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the TensorFlow tutorials.

If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.4733442e-08, 1.1931354e-07, 1.7938144e-05, 7.4855125e-05,
        1.6069951e-10, 2.3372659e-06, 1.7665248e-14, 9.9984944e-01,
        2.0124726e-07, 5.4970820e-05],
       [5.6572755e-08, 5.8283884e-04, 9.9924695e-01, 1.4026478e-04,
        2.0944394e-16, 2.6950722e-05, 1.5613686e-07, 2.4136609e-13,
        2.8438324e-06, 2.7037585e-14],
       [1.2795680e-07, 9.9874401e-01, 1.4855179e-04, 9.4665238e-06,
        6.0824470e-05, 2.4184994e-06, 1.0648697e-05, 6.7285920e-04,
        3.5067787e-04, 3.9157834e-07],
       [9.9998546e-01, 2.5674776e-10, 8.5867023e-06, 6.4394430e-07,
        3.7065057e-08, 1.3032022e-06, 3.5385742e-06, 1.7383105e-07,
        5.2102486e-08, 1.4609020e-07],
       [9.4975740e-06, 7.2387216e-09, 1.0810374e-05, 2.3601951e-08,
        9.9043953e-01, 4.1621021e-08, 9.3350423e-07, 1.0109208e-05,
        2.1567152e-07, 9.5289573e-03]], dtype=float32)>

## My Own Experiment
Now, I'm going to make a project with my own data and exploration. I am going to explore creating OCR models with Tensorflow and Keras.

In [14]:
import numpy as np

In [ ]:
# function to load the alphabet dataset
